"""
DbFixEngine
===========
Generates fix actions for database-layer root causes.

Supported fix_strategy values:
    add_column   → append ALTER TABLE statement to schema/db file
    fix_schema   → create a migration stub with instructional comment
    fix_seed     → create a safe seed stub
    unknown      → no-op

Never raises — all methods wrapped in try/except.
"""

import os
import re
import logging

logger = logging.getLogger(__name__)


# ── Templates ──────────────────────────────────────────────────────────────────

_ALTER_TABLE_STUB = """\
// AUTO-GENERATED by DbFixEngine — review before applying
// Run this in your database initialisation to add the missing column.
//
// db.exec(`ALTER TABLE {table} ADD COLUMN {column} TEXT DEFAULT NULL`);
"""

_MIGRATION_STUB = """\
// Migration stub — auto-generated by DbFixEngine
// Filename: server/migrations/{migration_name}
'use strict';

/**
 * Apply migration.
 * TODO: Fill in the correct SQL for your schema change.
 */
function up(db) {{
  // Example:
  // db.exec(`ALTER TABLE your_table ADD COLUMN new_col TEXT DEFAULT NULL`);
}}

/**
 * Rollback migration (optional).
 */
function down(db) {{
  // db.exec(`ALTER TABLE your_table DROP COLUMN new_col`);
}}

module.exports = {{ up, down }};
"""

_SEED_STUB = """\
// seed.ts — auto-generated safe stub by DbFixEngine
// Replace with your real seed data.
'use strict';

const Database = require('better-sqlite3');
const path     = require('path');

const DB_PATH = process.env.DB_PATH || path.join(__dirname, '..', 'database.sqlite');

function seed() {{
  const db = new Database(DB_PATH);
  try {{
    // db.prepare("INSERT INTO your_table (col1) VALUES (?)").run('value1');
    console.log('Seed completed.');
  }} catch (err) {{
    console.error('Seed failed:', err.message);
    process.exit(1);
  }} finally {{
    db.close();
  }}
}}

seed();
"""


class DbFixEngine:
    """
    Generates database fix actions from a root-cause dict.

    Usage:
        engine = DbFixEngine(sandbox_dir)
        actions = engine.generate_db_fix(root_cause, context)
    """

    def __init__(self, sandbox_dir: str):
        self.sandbox_dir = sandbox_dir

    def generate_db_fix(self, root_cause: dict, context: dict) -> list:
        """
        Main entry point.

        Args:
            root_cause: Structured decision/fix payload from the active triage pipeline
            context:    Output of ContextCollector.collect()

        Returns:
            List of action dicts.
        """
        strategy   = root_cause.get("fix_strategy", "unknown")
        raw_errors = root_cause.get("raw_errors", [])
        combined   = " ".join(raw_errors)

        try:
            if strategy == "add_column":
                return self._add_column(combined, context)
            elif strategy == "fix_schema":
                return self._fix_schema(combined, context)
            elif strategy == "fix_seed":
                return self._fix_seed(context)
            elif strategy == "resolve_sqlite_locking_issue":
                targets = root_cause.get("target_files", [])
                target_file = targets[0] if targets else "server/db/database.ts"
                return [{
                    "type": "ai_fix_required",
                    "file": target_file,
                    "error_detail": f"SQLite Locking Issue: {combined}",
                    "note": "Delegating complex SQLite WAL locking issue to AI for code modification (e.g., adding process.on('exit') graceful shutdown hooks)."
                }]
            else:
                logger.info(f"[DbFixEngine] No action for strategy='{strategy}', delegating to AI fallback")
                targets = root_cause.get("target_files", [])
                target_file = targets[0] if targets else "server/db/database.ts"
                return [{
                    "type": "ai_fix_required",
                    "file": target_file,
                    "error_detail": combined,
                    "note": f"Delegating unknown strategy '{strategy}' to AI."
                }]
        except Exception as exc:
            logger.error(f"[DbFixEngine] generate_db_fix raised: {exc}")
            return []

    # ── Strategies ─────────────────────────────────────────────────────────────

    def _add_column(self, error: str, context: dict) -> list:
        """
        Inject an ALTER TABLE stub into the schema/db initialisation file.
        Identifies the missing table+column from the SqliteError message.
        """
        # SqliteError: table X has no column named Y
        # SqliteError: no such column: Y
        table, column = self._extract_table_column(error)

        schema_files = context.get("database", {}).get("schema", [])
        target_file  = schema_files[0] if schema_files else None

        if not target_file:
            # Create a migration stub instead
            return self._fix_schema(error, context)

        full_path = os.path.join(self.sandbox_dir, target_file)
        try:
            with open(full_path, "r", encoding="utf-8", errors="ignore") as f:
                content = f.read()
        except OSError:
            content = ""

        stub = _ALTER_TABLE_STUB.format(table=table or "YOUR_TABLE", column=column or "missing_column")

        # Append the stub comment at the end of the schema file (safe — it's commented out)
        new_content = content.rstrip() + "\n\n" + stub
        return [{
            "type":    "update",
            "file":    target_file,
            "content": new_content,
            "note":    (
                f"Appended ALTER TABLE stub for column '{column}' in table '{table}'. "
                "Un-comment and adjust before next server start."
            ),
        }]

    def _fix_schema(self, error: str, context: dict) -> list:
        """
        Create a new migration stub file when the schema itself needs changing.
        Never overwrites — always creates a new timestamped migration file.
        """
        import time
        ts = int(time.time())
        migration_name = f"{ts}_auto_fix.ts"
        return [{
            "type":    "create",
            "file":    f"server/migrations/{migration_name}",
            "content": _MIGRATION_STUB.format(migration_name=migration_name),
            "note":    "Fill in the SQL in up() then run migrations before restarting.",
        }]

    def _fix_seed(self, context: dict) -> list:
        """
        Replace or create a safe seed stub that won't crash on boot.
        Only creates — does not overwrite existing seed.
        """
        seed_files = context.get("database", {}).get("seed", [])
        if seed_files:
            # Don't overwrite — generating a separate safe stub
            new_seed = "server/db/seed_safe.ts"
        else:
            new_seed = "server/db/seed.ts"

        full_path = os.path.join(self.sandbox_dir, new_seed)
        if os.path.exists(full_path):
            logger.info(f"[DbFixEngine] {new_seed} already exists — skipping")
            return []

        return [{
            "type":    "create",
            "file":    new_seed,
            "content": _SEED_STUB,
            "note":    "Safe seed stub created. Replace with real data before deploying.",
        }]

    # ── Helpers ────────────────────────────────────────────────────────────────

    @staticmethod
    def _extract_table_column(error: str):
        """Try to extract (table, column) from a SqliteError message."""
        # "table posts has no column named colour"
        m = re.search(r"table (\w+) has no column named (\w+)", error, re.IGNORECASE)
        if m:
            return m.group(1), m.group(2)
        # "no such column: posts.colour" or "no such column: colour"
        m = re.search(r"no such column:\s*(?:(\w+)\.)?(\w+)", error, re.IGNORECASE)
        if m:
            return m.group(1) or "unknown_table", m.group(2)
        return None, None
