"""
UIFixEngine — Self-Healing UI Generator
========================================

When RuntimeValidator.check_missing_ui() returns issues, this engine:
  1. Maps each issue to concrete React component/page files
  2. Generates code via LLM (or falls back to high-quality static templates)
  3. Safely writes files (backing up any existing content)
  4. Patches App.tsx to integrate new routes + imports

Safety guarantees:
  - Existing files are backed up before modification
  - New files are created only (never overwrite working components)
  - All methods are try/except wrapped — failures are logged, not raised
"""

import os
import re
import json
import logging
import shutil
from typing import Optional

logger = logging.getLogger(__name__)

# ── Static component templates ────────────────────────────────────────────────
# High-quality fallback templates used when no LLM provider is available.
# Each template is fully functional and follows the project patterns.

_NAVBAR_TEMPLATE = '''\
import React from "react";
import { Link, useLocation } from "react-router-dom";
import "./Navbar.css";

/**
 * Navbar — auto-generated by UIFixEngine
 * Extend this file with your project-specific links.
 */
export default function Navbar() {
  const { pathname } = useLocation();
  const links = [
    { to: "/",          label: "Home"     },
    { to: "/login",     label: "Login"    },
    { to: "/register",  label: "Register" },
  ];

  return (
    <nav className="navbar">
      <div className="navbar__brand">
        <Link to="/">MyApp</Link>
      </div>
      <ul className="navbar__links">
        {links.map(({ to, label }) => (
          <li key={to} className={pathname === to ? "active" : ""}>
            <Link to={to}>{label}</Link>
          </li>
        ))}
      </ul>
    </nav>
  );
}
'''

_NAVBAR_CSS_TEMPLATE = '''\
/* Navbar.css — auto-generated by UIFixEngine */
.navbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 1.5rem;
  height: 60px;
  background: #1a1a2e;
  color: #fff;
  position: sticky;
  top: 0;
  z-index: 100;
}
.navbar__brand a {
  font-size: 1.4rem;
  font-weight: 700;
  color: #e94560;
  text-decoration: none;
}
.navbar__links {
  display: flex;
  gap: 1.5rem;
  list-style: none;
  margin: 0;
  padding: 0;
}
.navbar__links a {
  color: #ccc;
  text-decoration: none;
  transition: color 0.2s;
}
.navbar__links .active a,
.navbar__links a:hover {
  color: #e94560;
}
'''

_LOGIN_TEMPLATE = '''\
import React, {{ useState }} from "react";
import api from "../services/api";
import "./Login.css";

/**
 * Login — auto-generated by UIFixEngine
 * Connects to /api/auth/login via POST.
 */
export default function Login() {{
  const [email,    setEmail]    = useState("");
  const [password, setPassword] = useState("");
  const [error,    setError]    = useState(null);
  const [loading,  setLoading]  = useState(false);

  async function handleSubmit(e) {{
    e.preventDefault();
    setLoading(true);
    setError(null);
    try {{
      const {{ data }} = await api.post("/auth/login", {{ email, password }});
      localStorage.setItem("token", data.token);
      window.location.href = "/";
    }} catch (err) {{
      setError(err.response?.data?.message || err.message);
    }} finally {{
      setLoading(false);
    }}
  }}

  return (
    <div className="auth-page">
      <form className="auth-form" onSubmit={{handleSubmit}}>
        <h1>Sign In</h1>
        {{error && <p className="auth-error">{{error}}</p>}}
        <label>
          Email
          <input
            type="email"
            value={{email}}
            onChange={{e => setEmail(e.target.value)}}
            required
            autoComplete="email"
          />
        </label>
        <label>
          Password
          <input
            type="password"
            value={{password}}
            onChange={{e => setPassword(e.target.value)}}
            required
            autoComplete="current-password"
          />
        </label>
        <button type="submit" disabled={{loading}}>
          {{loading ? "Signing in…" : "Sign In"}}
        </button>
        <p className="auth-switch">
          No account? <a href="/register">Register</a>
        </p>
      </form>
    </div>
  );
}}
'''

_REGISTER_TEMPLATE = '''\
import React, {{ useState }} from "react";
import api from "../services/api";
import "./Login.css";

/**
 * Register — auto-generated by UIFixEngine
 * Connects to /api/auth/register via POST.
 */
export default function Register() {{
  const [email,    setEmail]    = useState("");
  const [password, setPassword] = useState("");
  const [error,    setError]    = useState(null);
  const [loading,  setLoading]  = useState(false);

  async function handleSubmit(e) {{
    e.preventDefault();
    setLoading(true);
    setError(null);
    try {{
      const {{ data }} = await api.post("/auth/register", {{ email, password }});
      localStorage.setItem("token", data.token);
      window.location.href = "/login";
    }} catch (err) {{
      setError(err.response?.data?.message || err.message);
    }} finally {{
      setLoading(false);
    }}
  }}

  return (
    <div className="auth-page">
      <form className="auth-form" onSubmit={{handleSubmit}}>
        <h1>Create Account</h1>
        {{error && <p className="auth-error">{{error}}</p>}}
        <label>
          Email
          <input
            type="email"
            value={{email}}
            onChange={{e => setEmail(e.target.value)}}
            required
            autoComplete="email"
          />
        </label>
        <label>
          Password
          <input
            type="password"
            value={{password}}
            onChange={{e => setPassword(e.target.value)}}
            required
            autoComplete="new-password"
          />
        </label>
        <button type="submit" disabled={{loading}}>
          {{loading ? "Creating…" : "Create Account"}}
        </button>
        <p className="auth-switch">
          Already have an account? <a href="/login">Sign in</a>
        </p>
      </form>
    </div>
  );
}}
'''

_AUTH_CSS_TEMPLATE = '''\
/* Login.css — auto-generated by UIFixEngine */
.auth-page {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: #0f0f23;
}
.auth-form {
  background: #1a1a2e;
  padding: 2.5rem 2rem;
  border-radius: 12px;
  width: 100%;
  max-width: 400px;
  display: flex;
  flex-direction: column;
  gap: 1rem;
  color: #fff;
}
.auth-form h1 {
  margin: 0 0 0.5rem;
  font-size: 1.8rem;
  color: #e94560;
}
.auth-form label {
  display: flex;
  flex-direction: column;
  gap: 0.3rem;
  font-size: 0.9rem;
  color: #aaa;
}
.auth-form input {
  padding: 0.6rem 0.9rem;
  border: 1px solid #333;
  border-radius: 6px;
  background: #0f0f23;
  color: #fff;
  font-size: 1rem;
}
.auth-form button {
  padding: 0.75rem;
  background: #e94560;
  color: #fff;
  border: none;
  border-radius: 6px;
  font-size: 1rem;
  cursor: pointer;
  transition: opacity 0.2s;
}
.auth-form button:disabled { opacity: 0.6; cursor: default; }
.auth-error { color: #ff6b6b; font-size: 0.9rem; margin: 0; }
.auth-switch { text-align: center; color: #aaa; font-size: 0.85rem; }
.auth-switch a { color: #e94560; text-decoration: none; }
'''

_COMMENT_TEMPLATE = '''\
import React, {{ useState, useEffect }} from "react";
import api from "../services/api";
import "./CommentBox.css";

/**
 * CommentBox — auto-generated by UIFixEngine
 * Connects to /api/comments via GET + POST.
 */
export default function CommentBox({{ resourceId = null }}) {{
  const [comments, setComments] = useState([]);
  const [text,     setText]     = useState("");
  const [error,    setError]    = useState(null);
  const [loading,  setLoading]  = useState(false);

  const apiUrl = resourceId
    ? `{api_base}/comments?resourceId=${{resourceId}}`
    : "{api_base}/comments";

  useEffect(() => {{
    api.get(resourceId ? `/comments?resourceId=${{resourceId}}` : "/comments")
      .then(res => setComments(Array.isArray(res.data) ? res.data : res.data.comments ?? []))
      .catch(() => setComments([]));
  }}, [resourceId]);

  async function handleSubmit(e) {{
    e.preventDefault();
    if (!text.trim()) return;
    setLoading(true);
    setError(null);
    try {{
      const {{ data: newComment }} = await api.post("/comments", {{ text, resourceId }});
      setComments(prev => [newComment, ...prev]);
      setText("");
    }} catch (err) {{
      setError(err.message);
    }} finally {{
      setLoading(false);
    }}
  }}

  return (
    <section className="comment-box">
      <h2 className="comment-box__title">Comments</h2>
      <form className="comment-box__form" onSubmit={{handleSubmit}}>
        <textarea
          value={{text}}
          onChange={{e => setText(e.target.value)}}
          placeholder="Write a comment…"
          rows={{3}}
          required
        />
        {{error && <p className="comment-box__error">{{error}}</p>}}
        <button type="submit" disabled={{loading}}>
          {{loading ? "Posting…" : "Post Comment"}}
        </button>
      </form>
      <ul className="comment-box__list">
        {{comments.map((c, i) => (
          <li key={{c.id ?? i}} className="comment-box__item">
            <span className="comment-box__author">{{c.author ?? "Anonymous"}}</span>
            <p>{{c.text ?? c.body ?? c.content ?? ""}}</p>
          </li>
        ))}}
      </ul>
    </section>
  );
}}
'''

_COMMENT_CSS_TEMPLATE = '''\
/* CommentBox.css — auto-generated by UIFixEngine */
.comment-box {
  max-width: 680px;
  margin: 2rem auto;
  padding: 0 1rem;
  color: #ddd;
}
.comment-box__title {
  font-size: 1.4rem;
  color: #e94560;
  margin-bottom: 1rem;
}
.comment-box__form {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
  margin-bottom: 1.5rem;
}
.comment-box__form textarea {
  background: #1a1a2e;
  border: 1px solid #333;
  border-radius: 8px;
  color: #fff;
  font-size: 0.95rem;
  padding: 0.7rem;
  resize: vertical;
}
.comment-box__form button {
  align-self: flex-end;
  padding: 0.5rem 1.2rem;
  background: #e94560;
  color: #fff;
  border: none;
  border-radius: 6px;
  cursor: pointer;
  font-size: 0.95rem;
  transition: opacity 0.2s;
}
.comment-box__form button:disabled { opacity: 0.6; }
.comment-box__error { color: #ff6b6b; font-size: 0.85rem; }
.comment-box__list { list-style: none; padding: 0; display: flex; flex-direction: column; gap: 1rem; }
.comment-box__item {
  background: #1a1a2e;
  border-radius: 8px;
  padding: 0.8rem 1rem;
}
.comment-box__author { font-weight: 600; color: #e94560; font-size: 0.85rem; display: block; margin-bottom: 0.3rem; }
'''


# ── UIFixEngine ───────────────────────────────────────────────────────────────

class UIFixEngine:
    """
    Self-healing UI generator.

    Usage (from AgentLoop):
        engine = UIFixEngine(sandbox_dir, tool_registry, provider=self.provider)
        actions = await engine.generate_ui_fix(issues, context)
        for action in actions:
            await engine.apply_action(action)
        await engine.patch_app_jsx(actions)
    """

    UI_HEAL_MAX = 10  # max self-healing cycles (increased from 5 to 10)

    def __init__(self, sandbox_dir: str, tool_registry, provider=None):
        self.sandbox_dir   = sandbox_dir
        self.tool_registry = tool_registry
        self.provider      = provider   # Optional LLM provider for code gen
        self.logger        = logging.getLogger(__name__)

    # ── Public API ────────────────────────────────────────────────────────────

    async def generate_ui_fix(self, issues: list, context: dict) -> list:
        """
        Main entry point.

        Args:
            issues:  List of issue strings from check_missing_ui()
            context: Dict with keys: sandbox_dir, api_base, existing_files

        Returns:
            List of action dicts: {type, file, content}
        """
        actions = []
        seen_files: set = set()

        api_base = context.get("api_base", "/api")
        backend_routes = self._detect_backend_routes()

        for issue in issues:
            try:
                new_actions = self._map_issue_to_actions(
                    issue, api_base, backend_routes, context
                )
                for a in new_actions:
                    if a["file"] not in seen_files:
                        seen_files.add(a["file"])
                        actions.append(a)
            except Exception as e:
                self.logger.warning(f"[UIFixEngine] Mapping failed for '{issue}': {e}")

        self.logger.info(f"[UIFixEngine] Generated {len(actions)} fix action(s) for {len(issues)} issue(s)")
        return actions

    async def apply_action(self, action: dict) -> str:
        """
        Write a single action's file to disk.
        Backs up any existing file before overwriting.

        Returns a status string.
        """
        file_rel  = action.get("file", "")
        content   = action.get("content", "")
        file_type = action.get("type", "create")   # "create" | "update"

        if not file_rel or not content:
            return f"⚠️  Skipped empty action for {file_rel}"

        full_path = os.path.join(self.sandbox_dir, file_rel)

        try:
            # Backup existing file if this is an update
            if file_type == "update" and os.path.exists(full_path):
                backup = full_path + ".bak"
                shutil.copy2(full_path, backup)
                self.logger.debug(f"[UIFixEngine] Backed up {file_rel} → {os.path.basename(backup)}")

            # If creating and file already exists → skip (never overwrite working files)
            if file_type == "create" and os.path.exists(full_path):
                self.logger.info(f"[UIFixEngine] Skipped create — {file_rel} already exists")
                return f"↩️  Skipped (already exists): {file_rel}"

            await self.tool_registry.execute("write_file", {
                "path": file_rel,
                "content": content,
            })
            return f"✓ {'Updated' if file_type == 'update' else 'Created'}: {file_rel}"

        except Exception as e:
            self.logger.error(f"[UIFixEngine] Failed to write {file_rel}: {e}")
            return f"❌ Failed: {file_rel} ({e})"

    async def patch_app_jsx(self, actions: list) -> str:
        """
        Append import + <Route> statements to App.tsx for newly created pages.
        Only modifies App.tsx and only for page-level components under src/pages/.

        Returns a status string.
        """
        page_actions = [
            a for a in actions
            if a.get("file", "").startswith("src/pages/") and a["file"].endswith(".tsx")
        ]
        if not page_actions:
            return "No page-level actions — App.tsx not modified"

        app_path = os.path.join(self.sandbox_dir, "src", "App.tsx")
        if not os.path.exists(app_path):
            self.logger.warning("[UIFixEngine] App.tsx not found — skipping route patch")
            return "⚠️  App.tsx not found"

        try:
            with open(app_path, "r", encoding="utf-8") as f:
                app_content = f.read()

            # Backup
            shutil.copy2(app_path, app_path + ".bak")

            import_block = ""
            route_block  = ""

            for action in page_actions:
                file_rel  = action["file"]                         # src/pages/Login.tsx
                component = os.path.basename(file_rel)[:-4]        # Login
                rel_import = file_rel.replace("src/", "./")        # ./pages/Login

                # Skip if import already present
                if f"from \"{rel_import}\"" in app_content or f"from '{rel_import}'" in app_content:
                    continue

                import_block += f'import {component} from "{rel_import}";\n'
                route_block  += (
                    f'        <Route path="/{component.lower()}" '
                    f'element={{<{component} />}} />\n'
                )

            if not import_block:
                return "↩️  All routes already present in App.tsx"

            # Inject imports after the last existing import line
            patched = re.sub(
                r'((?:^import .+;\n)+)',
                lambda m: m.group(0) + import_block,
                app_content,
                count=1,
                flags=re.MULTILINE,
            )

            # Inject routes before the closing </Routes> or </Switch>
            patched = re.sub(
                r'(</Routes>|</Switch>)',
                route_block + r'\1',
                patched,
                count=1,
            )

            with open(app_path, "w", encoding="utf-8") as f:
                f.write(patched)

            return f"✓ App.tsx patched — added {len(page_actions)} route(s)"

        except Exception as e:
            self.logger.error(f"[UIFixEngine] App.tsx patch failed: {e}")
            return f"❌ App.tsx patch failed: {e}"

    async def inject_navbar(self) -> str:
        """
        Add <Navbar /> to App.tsx if Navbar exists and is not already imported.
        """
        app_path = os.path.join(self.sandbox_dir, "src", "App.tsx")
        if not os.path.exists(app_path):
            return "⚠️  App.tsx not found"

        try:
            with open(app_path, "r", encoding="utf-8") as f:
                content = f.read()

            if "Navbar" in content:
                return "↩️  Navbar already present in App.tsx"

            shutil.copy2(app_path, app_path + ".bak")

            # Add import
            patched = re.sub(
                r'((?:^import .+;\n)+)',
                r'\1import Navbar from "./components/Navbar";\n',
                content,
                count=1,
                flags=re.MULTILINE,
            )
            # Add <Navbar /> inside the first return ( ...
            patched = re.sub(
                r'(return\s*\(\s*\n\s*<)',
                r'return (\n      <>\n        <Navbar />\n        <',
                patched,
                count=1,
            )
            # Close the fragment (find matching closing tag of router/app root)
            patched = re.sub(
                r'(\n\s*\);?\s*\}\s*$)',
                r'\n      </>\n    );\n}\n',
                patched,
                count=1,
            )

            with open(app_path, "w", encoding="utf-8") as f:
                f.write(patched)

            return "✓ Navbar injected into App.tsx"
        except Exception as e:
            self.logger.error(f"[UIFixEngine] Navbar injection failed: {e}")
            return f"❌ Navbar inject failed: {e}"

    # ── Internal helpers ──────────────────────────────────────────────────────

    def _detect_backend_routes(self) -> list:
        """
        Scan server/routes/ and return a list of detected route keywords.
        E.g. ['auth', 'comment', 'post', 'user']
        """
        routes_dir = os.path.join(self.sandbox_dir, "server", "routes")
        if not os.path.isdir(routes_dir):
            return []
        keywords = []
        for fname in os.listdir(routes_dir):
            stem = fname.lower().replace("routes.ts", "").replace("route.ts", "").strip()
            if stem:
                keywords.append(stem)
        return keywords

    def _map_issue_to_actions(
        self,
        issue: str,
        api_base: str,
        backend_routes: list,
        context: dict,
    ) -> list:
        """
        Map a single issue string to a list of file actions.
        Falls back to static templates when no LLM provider is available.
        """
        issue_lower = issue.lower()
        actions = []

        # ── Navbar ────────────────────────────────────────────────────────────
        if any(kw in issue_lower for kw in ("navbar", "navigation", "nav")):
            actions += [
                {
                    "type": "create",
                    "file": "src/components/Navbar.tsx",
                    "content": _NAVBAR_TEMPLATE,
                    "integration": "navbar",
                },
                {
                    "type": "create",
                    "file": "src/components/Navbar.css",
                    "content": _NAVBAR_CSS_TEMPLATE,
                },
            ]

        # ── Login / Auth ──────────────────────────────────────────────────────
        if any(kw in issue_lower for kw in ("login", "auth", "signin", "sign in")):
            actions += [
                {
                    "type": "create",
                    "file": "src/pages/Login.tsx",
                    "content": _LOGIN_TEMPLATE.format(api_base=api_base),
                    "integration": "route",
                },
                {
                    "type": "create",
                    "file": "src/pages/Register.tsx",
                    "content": _REGISTER_TEMPLATE.format(api_base=api_base),
                    "integration": "route",
                },
                {
                    "type": "create",
                    "file": "src/pages/Login.css",
                    "content": _AUTH_CSS_TEMPLATE,
                },
            ]

        # ── Comments ──────────────────────────────────────────────────────────
        if any(kw in issue_lower for kw in ("comment", "discussion", "reply")):
            actions += [
                {
                    "type": "create",
                    "file": "src/components/CommentBox.tsx",
                    "content": _COMMENT_TEMPLATE.format(api_base=api_base),
                },
                {
                    "type": "create",
                    "file": "src/components/CommentBox.css",
                    "content": _COMMENT_CSS_TEMPLATE,
                },
            ]

        # ── Blank / minimal UI — trigger LLM if available, else report ────────
        if any(kw in issue_lower for kw in ("blank", "minimal", "empty")) and not actions:
            # We can't generate a generic app recovery without LLM context
            # — log and return empty so the caller falls back to _fix_unknown_error
            self.logger.warning(
                "[UIFixEngine] Blank UI issue detected but no specific template applies. "
                "Falling back to AI fix path."
            )

        return actions

    def _build_component_prompt(self, issue: str, context: dict) -> str:
        """Build an LLM prompt for generating a React component from an issue description."""
        existing_files = context.get("existing_files", [])
        api_base       = context.get("api_base", "/api")
        routes         = context.get("backend_routes", [])

        files_summary = "\n".join(existing_files[:20]) if existing_files else "(unknown)"
        routes_summary = ", ".join(routes) if routes else "(none detected)"

        return (
            f"You are a React developer. The frontend UI is missing the following feature:\n\n"
            f"ISSUE: {issue}\n\n"
            f"Backend API routes available: {routes_summary}\n"
            f"API base path: {api_base}\n\n"
            f"Existing project files (first 20):\n{files_summary}\n\n"
            "TASK: Generate the missing React component(s) as complete, production-quality JSX.\n"
            "Rules:\n"
            "  - Use React functional components with hooks\n"
            "  - Use the axios-based api service (src/services/api.ts) for ALL API calls — NEVER use raw fetch()\n"
            "  - Export as default\n"
            "  - Follow the existing project file structure (src/components for shared, src/pages for routes)\n"
            "  - Respond with ONLY code, no explanation\n"
            "  - Format: // FILE: <relative-path>\\n<code>\n"
        )
